POST http://localhost:3001/api/wilder/create HTTP/1.1
content-type: application/json

{
    "name":"Patrique",
    "City":"Londres",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}